#Formation parameters for determining the turtlebots' dynamic
K: 1.0
K_P: 30.0 # was 15.0
K_D: 10.0 # was 5.0
FORCE_GAIN: 10.0
MASS_BOT: 1.0
D: 2.5
DELAY_TIME: 1.0
SINGLE_TANK_: true
DELAYED_INPUTS_: false
NO_TANK_ : false
TANK_INITIAL_VALUE : 50
TANK_MAX_VALUE : 100
TANK_MIN_VALUE : 5
D_MAX_: 0.8
K_OBS_ : 15.0
SCALING_FACTOR : 30.0
MAX_FORCE: 2.0